config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :partners, only: [:index, :show, :new, :create, :destroy, :edit, :update] do
    resources :bookings, only: [:index, :show, :new, :create]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :partner
  belongs_to :user
end

app/models/partner.rb
class Partner < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_one_attached :photo
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  validates :name, presence: true
  validates :duty, presence: true
  validates :description, presence: true
  validates :address, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :partners
  has_many :bookings
  has_many :booked_partners, through: :bookings, source: :partner
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  include Pundit
  # Pundit: white-list approach.
  after_action :verify_authorized, except: [:index, :show, :new, :create], unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action!"
    redirect_to(partner_path)
  end

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:avatar_url])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:avatar_url])
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    if params[:query].present?
      sql_query = "name ILIKE :query OR duty ILIKE :query"
      @bookings = policy_scope(Booking).where(sql_query, query: "%#{params[:query]}%")
    else
      @bookings = policy_scope(Booking).where(user: current_user)
    end
    @partners = policy_scope(Partner).where(user: current_user)
    @lastbooking = Booking.last
  end

  def show
    @booking = Booking.find(params[:id])
  end

  def new
    @partner = Partner.find(params[:partner_id])
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.partner = Partner.find(params[:partner_id])
    if @booking.save!
      redirect_to partner_booking_path(@booking.partner, @booking)
    else
      render :new
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:start_time, :end_time, :date, :partner_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end
end

app/controllers/partners_controller.rb
class PartnersController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]
  def index
    @partners = policy_scope(Partner)
    @markers = @partners.geocoded.map do |partner|
      {
        lat: partner.latitude,
        lng: partner.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { partner: partner })

      }
    end

    if params[:query].present?
      sql_query = "name ILIKE :query OR duty ILIKE :query"
      @partners = policy_scope(Partner).where(sql_query, query: "%#{params[:query]}%")
      @error = "sorry we couldn't find a partner by this description" if @partners == []
    else
      @partners = policy_scope(Partner)
    end
  end

  def show
    @partner = Partner.find(params[:id])
    @booking = Booking.new
  end

  def new
    @partner = Partner.new
  end

  def create
    @partner = Partner.new(partner_params)
    @partner.user = current_user
    if @partner.save!
      redirect_to partner_path(@partner)
    else
      render :new
    end
  end

  def edit
    @partner = Partner.find(params[:id])
    authorize @partner
  end

  def update
    @partner = Partner.find(params[:id])
    authorize @partner
    if @partner.update(partner_params)
      redirect_to partner_path(@partner)
    else
      render :edit
    end
  end

  def destroy
    @partner = Partner.find(params[:id])
    authorize @partner
    @partner.destroy
    redirect_to partners_path
  end

  private

  def partner_params
    params.require(:partner).permit(:duty, :name, :gender, :age, :description, :photo, :url_photo, :address)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<div class="card-dashboard">
  <h1> Dashboard</h1>
  <div class="dashboard-view1">
  <h3>Your Last Booking</h3>
    <div class="booking-description">
      <strong>Starttime:</strong>
      <p><%= @lastbooking.start_time %></p>
      <strong>Endtime:</strong>
      <p><%= @lastbooking.end_time %></p>
      <strong>Date:</strong>
      <p><%= @lastbooking.date %></p>
    </div>
  </div>
  <div class="dashboard-view2">
    <h3>Your Bookings</h3>
    <% @bookings.each do |booking| %>
    <div>
    <p><strong>Name:</strong></p>
    <p><%= booking.partner.name %></p>
    <% if booking.partner.photo.attached?%>
          <%= cl_image_tag booking.partner.photo.key, height: 300, width: 400, crop: :fill %>
        <% else booking.partner.url_photo%>
          <p><%= cl_image_tag booking.partner.url_photo, height: 300, width: 400 %></p>
        <% end %>
    </div>
    <div>
      <strong>Starttime:</strong>
      <p><%= booking.start_time %></p>
      <strong>Endtime:</strong>
      <p><%= booking.end_time %></p>
      <strong>Date:</strong>
      <p><%= booking.date %></p>
    </div>
    <p>------------------------------------------------</p>
    <% end %>
  </div>
<%= link_to "keep pimping", partners_path, class: "btn btn-ghost" %>
</div>

app/views/bookings/new.html.erb
<div class="row justify-content-center">
  <div class="form-container mt-5">
    <div class="col-12">
      <h3>Make a new Booking</h3>
      <%= simple_form_for [@partner, @booking] do |f| %>
        <%= f.input :start_time %>
        <%= f.input :end_time %>
        <%= f.input :date %>


        <%= f.submit class: "btn btn-danger mt-3" %>
      <% end %>
      <%= link_to "Back to partner", "/partners/#{@partner.id}" %>
    </div>
  </div>
</div>

app/views/bookings/show.html.erb
<div class="booking-container">
  <h3><strong>Congratulation,</strong> your booking is confirmed!</h3>
  <div class="booking-description">
    <p>Starting Time: </p>
    <%= @booking.start_time %>
    <p>Ending Time: </p>
    <%= @booking.end_time %>
    <p>Date: </p>
    <%= @booking.date %>
  </div>
  <%= link_to " My Dashboard", partner_bookings_path, class: "btn btn-ghost" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PARTNERUP</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
    <%= render "shared/flashes" %>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner-home" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1558522195-e1201b090344?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2550&q=80);">
  <div class="container">
    <h1><strong>PartnerUp!</strong></h1>
    <p>Too busy to entertain your partner? - <strong>No problem!</strong></p>
    <a class="btn btn-success p-3" href="/partners">Get Pimpin</a>
  </div>
</div>

app/views/partners/_form.html.erb
<%= simple_form_for(partner) do |f| %>
  <!-- [...] -->
  <%= f.input :photo, as: :file %>
  <%= f.input :url_photo, as: :string %>
  <!-- [...] -->
<% end %>

<!-- <img src="https://images.unsplash.com/photo-1557333610-90ee4a951ecf?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1650&q=80" />
 -->

app/views/partners/_info_window.html.erb
<h2><%= partner.name %></h2>
<p><%= partner.address %></p>

app/views/partners/edit.html.erb
<div class="edit-container">
  <div class="col-12">
    <h3>Update your partners profile NOW</h3>
    <%= simple_form_for(@partner) do |f| %>
    <%= f.input :name %>
    <%= f.input :duty %>
    <%= f.input :description %>
    <%= f.input :address, id: "partner_address" %>
    <%= f.input :gender %>
    <%= f.input :age %>
    <%= f.input :photo, as: :file %>
    <p>or choose from web</p>
    <%= f.input :url_photo, as: :string %>
    <%= f.submit class: "btn btn-ghost" %>
    <% end %>
  <%#= link_to "Partner", partner_path, class: "btn btn-ghost" %>
 </div>
</div>

app/views/partners/index.html.erb
<!-- <div class="container" style="padding-top: 90px;"> -->
<%= render "shared/searchbar" %>
  <div class="d-flex w-100 mt-5 pt-5">
    <div class="col-12 col-md-6">
      <div class="row">
        <% if @partners == [] %>
        <div class="m-3">
          <h2><%= @error %></h2> <%= link_to "Go back",  "/partners", class: "btn btn-ghost"%>
        </div>
        <% else %>
          <% @partners.each do |partner| %>
            <div class="col-sm-6 col-md-6 col-xl-4 mb-4">
              <%= link_to partner_path(partner), class:"partner-card" do %>
              <div class="card-trip">
                <% if partner.photo.attached? %>
                  <%= cl_image_tag partner.photo.key, height: 400, width: 500 %>
                <% elsif partner.url_photo %>
                  <img src="<%= partner.url_photo %>">
                <% else %>
                <%= cl_image_tag("ej1l5rcyterspi4cwqht", width: 400, height: 300, crop: :fill) %>
                <% end %>
                <div class="card-trip-infos">
                  <div>
                    <h2><%= partner.duty %></h2>
                    <p><%= partner.description %></p>
                    <p><%= partner.age %></p>
                  </div>
                  <h2 class="card-trip-pricing"><%= partner.name %></h2>
  <!--                 <img src="<% partner.user.avatar_url %>" class="card-trip-user avatar-bordered" />
   -->              </div>
              </div>
              <% end %>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>

    <div class="col-12 col-md-6">
      <div id="map"
        style="width: 100%; height: 600px;"
        data-markers="<%= @markers.to_json %>"
        data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
    </div>
  </div>

app/views/partners/new.html.erb
<div class="add-container">
  <div class="col-12">
    <h3>Add a new Partner</h3>
    <%= simple_form_for(@partner) do |f| %>
    <%= f.input :name %>
    <%= f.input :gender %>
    <%= f.input :duty %>
    <%= f.input :description %>
    <%= f.input :age %>
    <%= f.input :address, id: "autocomplete-create" %>
    <%= f.input :photo, as: :file %>
    <p>or choose from web</p>
    <%= f.input :url_photo, as: :string %>
    <%= f.submit class: "btn btn-ghost" %>
    <% end %>

  <%#= link_to "Back to list", partners_path, class: "btn btn-ghost" %>
  </div>
</div>

app/views/partners/show.html.erb
<div class="card-show" >
  <div class="card-partner ">
    <div class="col-12">
      <div class="card-product">
        <% if @partner.photo.attached?%>
          <%= cl_image_tag @partner.photo.key, height: 500, width: 700, crop: :fill %>
        <% else @partner.url_photo%>
          <%= cl_image_tag @partner.url_photo, height: 500, width: 600 %>
        <% end %>
        <div class="card-product-infos">
          <h2><%= @partner.name %></h2>
          <p>Gender: <%= @partner.gender %></p>
          <p>Age: <%= @partner.age %></p>
          <p>Duty: <%= @partner.duty %></p>
        </div>
      </div>
      <div class="card-description" >
        <h3>Description:</h3>
        <p><%= @partner.description %></p>
        <% if policy(@partner).edit? %>
          <%= link_to "Update", edit_partner_path(@partner), class: "btn btn-ghost mt-3" %>
        <% end %>
        <% if policy(@partner).edit? %>
          <%= link_to "Remove Listing", partner_path(@partner[:id]), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-ghost mt-3" %>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card-booking">
    <div class="row justify-content">
      <div class="booking-form mt-5">
        <div class="col-12">
          <h3>Book now!</h3>
          <%= simple_form_for [@partner, @booking] do |f| %>
            <%= f.input :start_time %>
            <%= f.input :end_time %>
            <%= f.input :date %>
            <%= f.submit class: "btn btn-ghost mt-3" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<%# flash.each do |type, msg| %>
  <!-- <div class="alert alert-danger"> -->
    <%#= msg %>
  <!-- </div> -->
<%# end %>
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer mt-5">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    <i class="fas fa-heart"></i> - the Running buddy team
  </div>
</div>

app/views/shared/_searchbar.html.erb
<div id="search-bar">
  <%= form_tag partners_path, method: :get do %>
    <%= text_field_tag :query,
      params[:query],
      placeholder: "Find a partner", class: "p-2"
    %>
    <%= submit_tag "Search", class: "btn btn-primary p-2" %>
  <% end %>
</div>